gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio1 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio1 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio10 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio10 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio11 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio11 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio12 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio12
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio13 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio13 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio14 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio14 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio15 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio15 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio16 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio16
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio17 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio17 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio18 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio18 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio19 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio19 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio2 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio2
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio3 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio3 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio4 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio4 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio5 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio5 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio6 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio6
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio7 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio7 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio8 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio8 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.bio9 --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.bio9 &
gcta64 --mbfile Jregia_16chrs_Mbfiles --maf 0.05 --grm-sparse Jregia_16chrs_grm_SP_noSP --fastGWA-mlm-exact --pheno /pheno/JS_JR1_samples_env_data.altitude --qcovar Jregia_16chrs_pca.eigenvec --threads 30 --out JS_JR1_samples_env_data.altitude
